### ISSUE TITLE
Create nightly scripts for tests execution (softpipe)

### ISSUE THREAD

**Issue by tanty** [Igalia/mesa-dockerfiles#2]
We want some scripts that will pull the proper docker image and run the tests with the softpipes (llvmpipe, swr, swraster).

**Comment by tanty** [comment]
This is very similar to #3 .

I've added several changes to the Docker.piglit.jinja and, also, included a cronjob at crontab-daily-piglit.sh.

The script is added in our local server for a local user's crontab, like:

```
$ crontab -e
...
0 5 * * * bash <path_to>/crontab-daily-piglit.sh

```

This way, the script runs every night at 5. The job shouldn't have any output if there are no regressions. If there are regressions, we will get the summary of the changes and the html summary for the non-passing tests will be generated. Additionally, we will be receiving an email since I've added our real emails in the /etc/aliases file and the local exim4 is working.

We have to see how this works but this should be enough by now ...

**Comment by jasuarez** [comment]
I've noticed you are running both i965 and softpipe in a single `docker run` execution.

I think this is not the proper way. Rather, I would call docker run twice with an envvar, that contains `i965` or `softpipe` depending what do you want to run. Check vk-gl-cts dockerfile for an example.

This way we can run only one of them if required (like for a specific test), makes it easier to extend for new cases in future, without requiring to rebuild the container, and so on.

**Comment by tanty** [comment]
@jasuarez : done!

Now they run in separate "docker run" executions.

**Comment by tanty** [comment]
Still GL-CTS is missing.

**Comment by tanty** [comment]
GL-CTS is there but we are experiencing a regression by which not even piglit are now working with the software renderers

**Comment by tanty** [comment]
Now, it is working. @jasuarez found that we were not adding the gallium swrast driver.
