### ISSUE TITLE
Integrate ccache usage

### ISSUE THREAD

**Issue by tanty** [Igalia/mesa-dockerfiles#5]
Currently we buiild the mesa docker image without ccache support.

The idea is to create the docker image and, then, run a command to compile mesa. This way usage of ccache will be enable through a shared folder in travis.

**Comment by tanty** [comment]
I've checked slightly this.

In the Dockerfile.piglit.jinja there is a stupid attempt to do this. Afterwards, I realized that, since we cannot mount an external volume during build, my additions didn't have any effect.

After checking some documentation it seems that the way to go would be building the image without compiling the code. Then, run the image, compile with ccache (install, remove the code) and commit the changes to the image.

**Comment by jasuarez** [comment]
Fixed in commit 8e9f7a33d6ee3e2ab3
