### ISSUE TITLE
Build txc_dxtn conditional

### ISSUE THREAD

**Issue by jasuarez** [Igalia/mesa-dockerfiles#8]
libtxc-dxtn uses the patented S3 Texture Compression algorithm. Therefore, we don't want to use this library but it is still possible through setting the USE_TXC_DXTN variable to yes in the travis web UI.

 According to Wikipedia, the patent expires on October 2, 2017:
 https://en.wikipedia.org/wiki/S3_Texture_Compression#Patent

**Comment by tanty** [comment]
Fixed!
